### ISSUE TITLE
Connection check: censored: 'the output has been hidden due to the fact that ''no_log: true'' was specified for this result'

### ISSUE THREAD

**Issue by patsevanton** [lablabs/ansible-role-nexus_config#2]
Hello! Thanks for role nexus
I try install and get error
```
TASK [lablabs.nexus_config : Connection check] *****************************************************************************************************************************************
Sunday 27 March 2022  13:35:10 +0600 (0:00:04.506)       0:00:04.515 **********
fatal: [nexus -> localhost]: FAILED! =>
  censored: 'the output has been hidden due to the fact that ''no_log: true'' was specified for this result'

```

Playbook
```
---
- name: Configure Nexus
  hosts: nexus
  user: ubuntu
  become: yes
  vars:
    config:
      users:
        - id: joan
          first_name: Joan
          last_name: Doe
          email: joan@example.org
          password: "{{ lookup('env', 'JOAN_PASSWORD') }}"
          status: active
          source: default
          roles:
            - nx-admin
        - id: joe
          first_name: Joe
          last_name: Doe
          email: joe@example.org
          password: nbusr123
          status: disabled
          source: default
          roles:
            - nx-anonymous
      stores:
        - name: file_blob
          type: file
          soft_quota: 0
          path: /mydata/blobs
          status: active
  roles:
    - role: lablabs.nexus_config
```

Version
```
ansible [core 2.12.2]
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
```

Server where ansible
```
cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
```

Remote server
```
cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
```
